'use client';

import { useEffect, useRef, useState } from 'react';

import ArticleSection from '../../../components/braitenberg/article-section';
import Callout from '../../../components/braitenberg/callout';
import FigureBlock from '../../../components/braitenberg/figure-block';
import {
  ActionButton,
  ControlRow,
  RangeControl,
} from '../../../components/braitenberg/control-row';
import EssayShell from '../../../components/essay-shell';
import { makeEngine } from './engine';

export default function MapPage() {
  return (
    <EssayShell
      dek="Take a city you know. Pick the part that's rich, pick the part that isn't, and ask who decided the line between them. History supplies no shortage of culprits. But Thomas Schelling asked a quieter question: what if the line appears even when nobody draws it?"
      readingTime="10 min read"
      title="The map that nobody drew"
    >
      <ArticleSection>
        <p>
          He built the smallest possible city. Two kinds of households. Some
          empty space. One mild preference: I am comfortable if enough of my
          neighbours are like me. If not, I move.
        </p>
        <p>
          Then he repeated the decision. The result was not a gently textured
          neighbourhood. It was a border. The unsettling claim is not that
          cities are simple. It is that some of their largest visible patterns
          can be generated by a model with almost nothing in it.
        </p>
        <p>
          Density gradients, districts, ethnic enclaves, dead seams between
          neighbourhoods: again and again the macro-pattern falls out of the
          same machine. You do not need to model a city. You need to model a
          decision, repeated.
        </p>
      </ArticleSection>

      <ArticleSection title="The Map That Nobody Drew">
        <p>
          Urban history is full of explicit decisions. Zoning boards draw hard
          edges. Banks ration credit. Highways are pushed through the wrong
          neighbourhood. The point of Schelling&apos;s model is not to erase any of
          that. It is to isolate a second force.
        </p>
        <p>
          Suppose nobody plans the final map. Suppose each household only asks a
          local question about comfort. Not purity. Not domination. Just enough
          familiarity to stay put.
        </p>
        <p>
          Braitenberg&apos;s trick was always to build the vehicle first and only
          then name what it seems to feel like from outside. The Schelling city
          rewards the same approach. Look at the map first. Ask who wanted it.
          Only then inspect the rule.
        </p>
      </ArticleSection>

      <Callout label="Key idea">
        <p>
          In Schelling&apos;s model,
          <strong> micro-tolerance becomes macro-segregation</strong>. No
          resident asks for a monochrome district. The repeated rule asks for
          one on their behalf.
        </p>
      </Callout>

      <ArticleSection title="The Model With Almost Nothing In It">
        <p>
          The vehicle is almost insulting in its simplicity. Each household
          occupies a square on a grid. It inspects its immediate neighbours. If
          the share of similar neighbours drops below a threshold, it moves to
          an empty square. Repeat.
        </p>
        <p>
          That is enough. No one sees the whole city. No one reasons about
          demographics. No one intends a ghetto. Yet as the rule iterates, the
          line appears anyway.
        </p>
      </ArticleSection>

      <Sim1 />

      <ArticleSection title="The Gap">
        <p>
          The emotional centre of the model is the gap between what feels mild
          and what looks extreme. A household that is content with only a third
          of its neighbours being similar does not sound fanatical. But iterate
          that threshold across a whole city and the collective outcome drifts
          toward near-total sorting.
        </p>
        <p>
          The reason is mechanical. Each move that relieves one household
          slightly changes the composition around somebody else. Local comfort is
          contagious. So is local discomfort. The city is not complicated. The
          city is iterated.
        </p>
      </ArticleSection>

      <Sim2 />

      <ArticleSection title="Three Is Enough">
        <p>
          Once you see the grammar, Schelling stops looking unique. Other
          systems with similarly tiny rule sets produce the same kind of
          surprise: rich geometry with almost no intelligence inside it.
        </p>
        <p>
          The city starts to look less like a masterpiece of planning and more
          like a stable pattern produced by repeated local updates.
        </p>
      </ArticleSection>

      <RuleCards />

      <ArticleSection>
        <p>
          Boids give you spontaneous lanes on a crowded pavement. Cellular
          automata give you pulses of crowding, abandonment, and return.
          Reaction-diffusion gives you stripes and bands, as if a city could
          grow districts the way a fish grows markings.
        </p>
        <p>
          The common structure is small. A local state, a local rule, a loop.
          The wonder is that this is enough. The horror is that it is enough.
        </p>
      </ArticleSection>

      <ArticleSection title="Vacancy, Districts, and the Death of Streets">
        <p>
          Movement requires slack. In Schelling&apos;s world, empty squares are not
          background. They are the channels that let households reshuffle. A
          little vacancy lubricates sorting. More vacancy creates visible seams:
          wide buffers, islands of similarity, streets that stop serving as
          bridges and start serving as borders.
        </p>
        <p>
          That is one reason abandonment feels urban rather than merely empty.
          It changes the dynamics of who can move where, and which local
          decisions have somewhere to go.
        </p>
      </ArticleSection>

      <Sim3 />

      <ArticleSection title="What This Means for Blame">
        <p>
          This is the philosophical payload, and it cuts both ways. If nobody
          explicitly chose the final pattern, the pattern can still be unjust.
          Emergence is not innocence.
        </p>
        <p>
          History still matters because history sets the initial conditions. It
          decides who can move, who can borrow, which streets are cut in half,
          where the empty housing stock is, and how expensive discomfort is. The
          model does not absolve redlining. It shows how a city can keep
          rewriting an old intention long after the planner has left the room.
        </p>
        <p>
          That is why Schelling&apos;s little grid still unsettles. A city can end
          up looking designed when all you really gave it was repetition.
        </p>
      </ArticleSection>

      <Sandbox />
    </EssayShell>
  );
}

function Sim1() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const likeRef = useRef<HTMLSpanElement>(null);
  const unhappyRef = useRef<HTMLSpanElement>(null);

  useEffect(() => {
    if (!canvasRef.current) {
      return;
    }

    const parent = canvasRef.current.parentElement;

    if (parent) {
      canvasRef.current.width = parent.clientWidth;
    }

    let engine: any = null;

    const observer = new IntersectionObserver(
      (entries) => {
        if (!entries[0].isIntersecting || !canvasRef.current) {
          return;
        }

        engine = makeEngine(canvasRef.current, {
          threshold: 0.34,
          vacancy: 0.12,
          onTick({ meanLike, unhappyRate }) {
            if (likeRef.current) {
              likeRef.current.textContent = meanLike.toFixed(2);
            }

            if (unhappyRef.current) {
              unhappyRef.current.textContent = `${Math.round(
                unhappyRate * 100
              )}%`;
            }
          },
        });

        engine?.start();
        observer.disconnect();
      },
      { threshold: 0.05 }
    );

    observer.observe(canvasRef.current);

    return () => {
      observer.disconnect();
      engine?.cleanup();
    };
  }, []);

  return (
    <FigureBlock
      caption="A mild threshold and a little empty space are enough for sharp local clusters to appear. Small centre squares mark households that still want to move."
      figure="01"
      label="Emergent segregation"
    >
      <div className="overflow-hidden bg-white">
        <canvas ref={canvasRef} className="block w-full bg-white" height={240} />
      </div>
      <p className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-[11px] uppercase tracking-[0.22em] text-stone-700">
        <span>
          Same-neighbour share{' '}
          <strong className="font-semibold text-black" ref={likeRef}>
            0.50
          </strong>
        </span>
        <span>
          Unhappy households{' '}
          <strong className="font-semibold text-black" ref={unhappyRef}>
            0%
          </strong>
        </span>
      </p>
    </FigureBlock>
  );
}

function Sim2() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const engineRef = useRef<any>(null);
  const likeRef = useRef<HTMLSpanElement>(null);
  const unhappyRef = useRef<HTMLSpanElement>(null);
  const [threshold, setThreshold] = useState(0.3);

  useEffect(() => {
    if (!canvasRef.current) {
      return;
    }

    const parent = canvasRef.current.parentElement;

    if (parent) {
      canvasRef.current.width = parent.clientWidth;
    }

    const observer = new IntersectionObserver(
      (entries) => {
        if (!entries[0].isIntersecting || !canvasRef.current) {
          return;
        }

        engineRef.current = makeEngine(canvasRef.current, {
          threshold,
          vacancy: 0.12,
          onTick({ meanLike, unhappyRate }) {
            if (likeRef.current) {
              likeRef.current.textContent = meanLike.toFixed(2);
            }

            if (unhappyRef.current) {
              unhappyRef.current.textContent = `${Math.round(
                unhappyRate * 100
              )}%`;
            }
          },
        });

        engineRef.current?.start();
        observer.disconnect();
      },
      { threshold: 0.05 }
    );

    observer.observe(canvasRef.current);

    return () => {
      observer.disconnect();
      engineRef.current?.cleanup();
      engineRef.current = null;
    };
  }, []);

  useEffect(() => {
    if (!engineRef.current) {
      return;
    }

    engineRef.current.p.threshold = threshold;
    engineRef.current.reset();
  }, [threshold]);

  return (
    <FigureBlock
      caption="Raise the tolerance threshold and the city sorts harder. Lower it and mixed edges persist for longer, but the aggregate still drifts toward clustering."
      figure="02"
      label="Tolerance gap"
    >
      <div className="overflow-hidden bg-white">
        <canvas ref={canvasRef} className="block w-full bg-white" height={240} />
      </div>
      <ControlRow>
        <RangeControl
          label="Tolerance threshold"
          max={0.75}
          min={0.1}
          onChange={setThreshold}
          step={0.01}
          value={threshold}
          valueLabel={threshold.toFixed(2)}
        />
        <ActionButton onClick={() => engineRef.current?.reset()}>Reset city</ActionButton>
      </ControlRow>
      <p className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-[11px] uppercase tracking-[0.22em] text-stone-700">
        <span>
          Same-neighbour share{' '}
          <strong className="font-semibold text-black" ref={likeRef}>
            0.50
          </strong>
        </span>
        <span>
          Unhappy households{' '}
          <strong className="font-semibold text-black" ref={unhappyRef}>
            0%
          </strong>
        </span>
      </p>
    </FigureBlock>
  );
}

function RuleCards() {
  return (
    <section className="grid gap-4 md:grid-cols-3">
      <div className="border border-stone-300 p-5">
        <p className="text-[11px] uppercase tracking-[0.24em] text-stone-700">
          Boids
        </p>
        <h3 className="mt-3 font-serif text-2xl font-normal tracking-tight text-stone-950">
          Flow without traffic lights
        </h3>
        <p className="mt-3 text-[1rem] leading-7 text-black">
          Separation, alignment, cohesion. That is enough for pedestrians to
          sort into lanes and for a crowd to discover a flow field without a
          planner.
        </p>
      </div>
      <div className="border border-stone-300 p-5">
        <p className="text-[11px] uppercase tracking-[0.24em] text-stone-700">
          Cellular automata
        </p>
        <h3 className="mt-3 font-serif text-2xl font-normal tracking-tight text-stone-950">
          Density as a threshold effect
        </h3>
        <p className="mt-3 text-[1rem] leading-7 text-black">
          Birth, death, crowding. Tiny occupancy rules can produce slum
          formation, gentrification waves, and sudden abandonment without anyone
          orchestrating the transition.
        </p>
      </div>
      <div className="border border-stone-300 p-5">
        <p className="text-[11px] uppercase tracking-[0.24em] text-stone-700">
          Reaction-diffusion
        </p>
        <h3 className="mt-3 font-serif text-2xl font-normal tracking-tight text-stone-950">
          Districts like animal markings
        </h3>
        <p className="mt-3 text-[1rem] leading-7 text-black">
          An activator and an inhibitor are enough to generate stripes, spots,
          and territorial bands. The city starts to look like a patterned skin.
        </p>
      </div>
    </section>
  );
}

function Sim3() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const engineRef = useRef<any>(null);
  const likeRef = useRef<HTMLSpanElement>(null);
  const vacancyRef = useRef<HTMLSpanElement>(null);
  const [vacancy, setVacancy] = useState(0.18);

  useEffect(() => {
    if (!canvasRef.current) {
      return;
    }

    const parent = canvasRef.current.parentElement;

    if (parent) {
      canvasRef.current.width = parent.clientWidth;
    }

    const observer = new IntersectionObserver(
      (entries) => {
        if (!entries[0].isIntersecting || !canvasRef.current) {
          return;
        }

        engineRef.current = makeEngine(canvasRef.current, {
          threshold: 0.34,
          vacancy,
          onTick({ meanLike, vacancy: actualVacancy }) {
            if (likeRef.current) {
              likeRef.current.textContent = meanLike.toFixed(2);
            }

            if (vacancyRef.current) {
              vacancyRef.current.textContent = `${Math.round(
                actualVacancy * 100
              )}%`;
            }
          },
        });

        engineRef.current?.start();
        observer.disconnect();
      },
      { threshold: 0.05 }
    );

    observer.observe(canvasRef.current);

    return () => {
      observer.disconnect();
      engineRef.current?.cleanup();
      engineRef.current = null;
    };
  }, []);

  useEffect(() => {
    if (!engineRef.current) {
      return;
    }

    engineRef.current.reset({ vacancy });
  }, [vacancy]);

  return (
    <FigureBlock
      caption="Empty cells are mobility channels. Increase vacancy and the model produces thicker buffers, clearer districts, and the beginnings of dead space between them."
      figure="03"
      label="Vacancy as urban slack"
    >
      <div className="overflow-hidden bg-white">
        <canvas ref={canvasRef} className="block w-full bg-white" height={240} />
      </div>
      <ControlRow>
        <RangeControl
          label="Vacancy"
          max={0.35}
          min={0.05}
          onChange={setVacancy}
          step={0.01}
          value={vacancy}
          valueLabel={vacancy.toFixed(2)}
        />
        <ActionButton onClick={() => engineRef.current?.reset()}>Reset city</ActionButton>
      </ControlRow>
      <p className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-[11px] uppercase tracking-[0.22em] text-stone-700">
        <span>
          Same-neighbour share{' '}
          <strong className="font-semibold text-black" ref={likeRef}>
            0.50
          </strong>
        </span>
        <span>
          True vacancy{' '}
          <strong className="font-semibold text-black" ref={vacancyRef}>
            0%
          </strong>
        </span>
      </p>
    </FigureBlock>
  );
}

function Sandbox() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const engineRef = useRef<any>(null);
  const likeRef = useRef<HTMLSpanElement>(null);
  const unhappyRef = useRef<HTMLSpanElement>(null);
  const vacancyRef = useRef<HTMLSpanElement>(null);
  const [threshold, setThreshold] = useState(0.34);
  const [vacancy, setVacancy] = useState(0.14);

  useEffect(() => {
    if (!canvasRef.current) {
      return;
    }

    const parent = canvasRef.current.parentElement;

    if (parent) {
      canvasRef.current.width = parent.clientWidth;
    }

    const engine = makeEngine(canvasRef.current, {
      threshold,
      vacancy,
      cellSize: 10,
      sweepsPerFrame: 4,
      onTick({ meanLike, unhappyRate, vacancy: actualVacancy }) {
        if (likeRef.current) {
          likeRef.current.textContent = meanLike.toFixed(2);
        }

        if (unhappyRef.current) {
          unhappyRef.current.textContent = `${Math.round(unhappyRate * 100)}%`;
        }

        if (vacancyRef.current) {
          vacancyRef.current.textContent = `${Math.round(
            actualVacancy * 100
          )}%`;
        }
      },
    });

    engineRef.current = engine;
    engine?.start();

    return () => engine?.cleanup();
  }, []);

  useEffect(() => {
    if (!engineRef.current) {
      return;
    }

    engineRef.current.p.threshold = threshold;
    engineRef.current.reset({ threshold, vacancy });
  }, [threshold, vacancy]);

  return (
    <FigureBlock
      caption="Open the city directly. Change only the local rule and the amount of slack, then watch how much urban history the map seems to acquire all by itself."
      figure="04"
      label="Open plate"
    >
      <div className="overflow-hidden bg-white">
        <canvas ref={canvasRef} className="block w-full bg-white" height={360} />
      </div>
      <div className="grid gap-8 border-t border-stone-300 pt-4 md:grid-cols-[minmax(0,1fr)_220px]">
        <div className="space-y-2">
          <RangeControl
            label="Tolerance threshold"
            max={0.75}
            min={0.1}
            onChange={setThreshold}
            step={0.01}
            value={threshold}
            valueLabel={threshold.toFixed(2)}
          />
          <RangeControl
            label="Vacancy"
            max={0.35}
            min={0.05}
            onChange={setVacancy}
            step={0.01}
            value={vacancy}
            valueLabel={vacancy.toFixed(2)}
          />
          <div className="px-2 py-1">
            <ActionButton onClick={() => engineRef.current?.reset()}>
              Randomize map
            </ActionButton>
          </div>
        </div>
        <div className="space-y-3 border-l border-stone-300 pl-5 text-[11px] uppercase tracking-[0.22em] text-stone-700">
          <p>
            Same-neighbour share{' '}
            <strong className="font-semibold text-black" ref={likeRef}>
              0.50
            </strong>
          </p>
          <p>
            Unhappy households{' '}
            <strong className="font-semibold text-black" ref={unhappyRef}>
              0%
            </strong>
          </p>
          <p>
            Vacancy{' '}
            <strong className="font-semibold text-black" ref={vacancyRef}>
              0%
            </strong>
          </p>
        </div>
      </div>
    </FigureBlock>
  );
}
