import type { Metadata } from 'next';

import ArticleSection from '../../../../components/braitenberg/article-section';
import ArticleShell from '../../../../components/braitenberg/article-shell';
import Callout from '../../../../components/braitenberg/callout';
import FigureBlock from '../../../../components/braitenberg/figure-block';
import ShapeLab from '../../../../components/braitenberg/shape-lab';

export const metadata: Metadata = {
  title: 'Vehicle 9: Shapes',
  description:
    'A Braitenberg-inspired interactive essay about shape perception as a temporal signature rather than a static snapshot.',
};

export default function VehicleNinePage() {
  return (
    <ArticleShell
      dek="Shape becomes less mysterious once it is treated as a sequence of sensor changes over a scan rather than as a fully formed picture delivered all at once."
      readingTime="9 min read"
      slug="vehicle-9-shapes"
    >
      <ArticleSection>
        <p>
          Shape perception often gets described as if the whole form were simply
          present to the system at once. Braitenberg’s framing points in a more
          incremental direction. A shape can be recognized through the way a
          sensor signal unfolds over time.
        </p>
        <p>
          This matters because it ties form back to interaction. The signature
          of a square, a circle, or a triangle is not just the figure itself but
          the temporal pattern produced by scanning across it.
        </p>
      </ArticleSection>

      <Callout label="Key idea">
        <p>
          A shape can be encoded as a changing relation over time. Recognition
          begins when the system becomes sensitive to the signature of that
          unfolding.
        </p>
      </Callout>

      <ArticleSection title="The signature is often enough">
        <p>
          If a sensor sweep produces a distinctive pattern, the mechanism does
          not need a high-resolution image to differentiate forms. It only needs
          to become sensitive to the profile generated by the scan.
        </p>
      </ArticleSection>

      <FigureBlock
        caption="The left panel shows a scanned shape; the right panel shows the signal signature produced across the sweep."
        figure="9a"
        label="Scan signature"
      >
        <ShapeLab variant="scan" />
      </FigureBlock>

      <ArticleSection title="Form is learned as a relation">
        <p>
          The broader lesson is that perception is rarely a single instant. It
          is often the stabilization of a relation between body, sensor, and
          world over time. Shapes are one clear example of that rule.
        </p>
      </ArticleSection>

      <FigureBlock
        caption="Switch shapes and change the aperture. The signal changes because form is being encountered as an unfolding pattern, not a static fact."
        figure="9b"
        label="Open scanner"
      >
        <ShapeLab variant="sandbox" />
      </FigureBlock>
    </ArticleShell>
  );
}
